language: node_js
node_js:
 - "node"

cache: yarn 

script: 
  - (echo "VUE_APP_BACKEND_BASE_URL='https://hanabi-backend.herokuapp.com/'") >> .env 
  - yarn run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: master
